 const users = [
  {
    name: "Aaron Rodgers",
    username: "Choker",
    password: "iNeedToGo",
    email: "packersSuck@gmail.com",
    location: "Somewhere, Wisconson",
    admin: false,
  },
  {
    name: "Mr Brady",
    username: "seniorCitizen",
    password: "iNeedToRetire",
    email: "myBackHurts@gmail.com",
    location: "Tampa, Florida",
    admin: false,
  },
  {
    name: "Ryan Fitzpatrick",
    username: "wanderer",
    password: "iAmAdequate",
    email: "whoDoesHePlayFor@gmail.com",
    location: "Anywhere, Florida",
    admin: false,
  },

  {
    name: "Dustin",
    username: "saints4life",
    password: "SuperBowlChamps",
    email: "whodat@gmail.com",
    location: "Lafayette, Louisana",
    admin: true,
  },
  {
    name: "Drew Brees",
    username: "whodatking",
    password: "ihavehairplugs",
    email: "neworleanssaints@gmail.com",
    location: "Lafayette, Louisana",
    admin: false,
  },
  {
    name: "Peyton Manning",
    username: "PapaJohnKing",
    password: "ihavea5head",
    email: "coltsandbroncos@gmail.com",
    location: "Laffayette, Louisana",
    admin: false,
  },
  {
    name: "Rus Wilson",
    username: "broncoscountry",
    password: "LetRide!",
    email: "broncoscountryletsride@gmail.com",
    location: "Laffayette, Louisana",
    admin: false,
  },
  {
    name: "Jon Gruden",
    username: "qbcamp",
    password: "SerpentineSon!",
    email: "football@gmail.com",
    location: "Laffayette, Louisana",
    admin: false,
  },
  {
    name: "Jay Cutler",
    username: "idonotcare",
    password: "Ihatefootball$$",
    email: "idonotcare@gmail.com",
    location: "Laffayette, Louisana",
    admin: false,
  },
  {
    name: "Vikings",
    username: "vikings",
    password: "password",
    email: "fsvikings@gmail.com",
    location: "Cleveland, Ohio",
    admin: true,
  },
];

module.exports = { users } 